name: Daily Performance Test Java 25

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  performance-test:
    uses: ./.github/workflows/performance-test-base.yml
    with:
      javaVersion: "25"